In [1]:
from sympy import *
import numpy as np
import pandas as pd
init_printing(use_unicode=False, wrap_line=False, no_global=True)

In [2]:
Matr=[[[-1,7,-34],[8,8,-48]],
      [[4,-7,-4],[3,-4,-3]],
      [[8,-4,64],[-3,3,-21]],
      [[5,7,-5,-47],[0,-2,2,10],[-4,-8,-7,63]]]
for i in Matr:
    f = Matrix(i)
    display(f,linsolve(f))
    print('\n\n')
    


[-1  7  -34]
[          ]
[8   8  -48]

[4  -7  -4]
[         ]
[3  -4  -3]

[8   -4  64 ]
[           ]
[-3  3   -21]

[5   7   -5  -47]
[               ]
[0   -2  2   10 ]
[               ]
[-4  -8  -7  63 ]

In [3]:
matr=[[[-1,7],[8,8]],
      [[4,-7],[3,-4]],
      [[8,-4],[3,-3]],
      [[5,7,-5],[0,-2,2],[-4,-8,-7]]]
matr_b=[[-1,-5],[-1,0],[9,2],[-2,-6,-1]]
    


In [4]:
for i in range(len(matr)):
    M=Matrix(matr[i])
    MB=Matrix(matr_b[i])
    display(M,MB,M*MB)
    print('-'*50)

[-1  7]
[     ]
[8   8]

[-1]
[  ]
[-5]

[-34]
[   ]
[-48]

--------------------------------------------------


[4  -7]
[     ]
[3  -4]

[-1]
[  ]
[0 ]

[-4]
[  ]
[-3]

--------------------------------------------------


[8  -4]
[     ]
[3  -3]

[9]
[ ]
[2]

[64]
[  ]
[21]

--------------------------------------------------


[5   7   -5]
[          ]
[0   -2  2 ]
[          ]
[-4  -8  -7]

[-2]
[  ]
[-6]
[  ]
[-1]

[-47]
[   ]
[10 ]
[   ]
[63 ]

--------------------------------------------------


In [6]:
# Создалим  функцию, которая будет создавать алгебраическое выражение для 
# MSE  любой переопределенной системы уравнений.
list_a=[]
list_x=[]
system=[[5,7,-5],[0,-2,2],[-4,-8,-7],[1,1,2],[2,-1,2],[4,1,4]]
rez=[-47,10,63,-1,-4,-2]
for i in range(len(system[0])):
        list_a.append(Symbol('a'+str(i)))
        list_x.append(Symbol('x'+str(i)))



def mse(system,rez):
    """Функция на входе принимает два обязательных  параметра
    system итерируемый объект из списков(или других итерируемых объектов)
    коэффициентов линейных уравнений
    rez итерируемый объект результатов уравнений"""
    list_a=[]
    list_x=[]
    for i in range(len(system[0])):
        list_a.append(Symbol('a'+str(i)))
        list_x.append(Symbol('x'+str(i)))
    f=np.sum(np.array(list_a)*np.array(list_x))
    MSE=0
    for j,i in enumerate(system):
        MSE = MSE + (f.subs({'x0':i[0], 'x1':i[1],'x2': i[2]})-rez[j])**2
    return MSE/len(system)
MSE=mse(system,rez)
MSE


In [7]:
list_dif=[]
for i in list_a:
    list_dif.append(diff(MSE,i))
list_dif

In [8]:
sol=nonlinsolve(list_dif,list_a).args[0]
sol

In [9]:
g=f.subs({'a0':sol[0],'a1':sol[1], 'a2':sol[2]})
g

[5   7   -5  -47]
[               ]
[0   -2  2   10 ]
[               ]
[-4  -8  -7  63 ]

In [10]:
MSE.subs({'a0':sol[0],'a1':sol[1], 'a2':sol[2]})

In [11]:
2803093/76746

Теперь посчитаем это же методом градиентного спуска
Возьмем три произвольных значения   
a1=1,   
a2=1,  
a3=1


In [12]:
def regr(point,MSE_aim,learning_rate):
    """
    function for searching coefficiens of redifined system of lineal equations
    
    
    parametrs:
        point - first point for search
    MSE_aim aim fo MSE, you want to get
    learning_rate - step for gradient descent
    
    display time start, time end,
    MSE Value
    return tuple:
    dict points, val
    """
    
        
    
    dict_point={}
    xt=pd.Timestamp.now()
    print('время начала ',xt)
    for h,k in enumerate(list_a):
         dict_point[list_a[h]]=point[h]
    list_Mse=[]
    while MSE.subs(dict_point)>MSE_aim:
        
        
        for i in range(len(point)):
            point[i]=  point[i]-diff(MSE,list_a[i]).subs(dict_point)*learning_rate
            dict_point[list_a[i]]=point[i]

    yt=pd.Timestamp.now()   
    print('время окончания ',yt)
    print(MSE.subs(dict_point))
    print ('затрачено время',(yt-xt))
    return (dict_point,{'MSE':MSE.subs(dict_point)})


In [13]:
point=[0,0,0]
MSE_aim = 55
learning_rate=0.01

regr(point,MSE_aim,learning_rate)

время начала  2021-05-01 11:45:09.945034
время окончания  2021-05-01 11:45:10.445804
53.6223922644693
затрачено время 0 days 00:00:00.500770


({a0: -2.25776878131059, a1: -5.58732958379538, a2: -0.304690516522426},
 {'MSE': 53.6223922644693})

не очень согласуется с полученным до этого результатом. попробуем более жестко установить рамки MSE, например, то значение, которое мы получили решая через систмему линейных уравнений. 
MSE= 36.5242879107706

In [14]:
point=[1,1,1]
MSE_aim = 36.5242879107706
learning_rate=0.01

coeff=regr(point,MSE_aim,learning_rate)
coeff

время начала  2021-05-01 11:45:15.517070
время окончания  2021-05-01 11:45:32.653162
36.5242879107706
затрачено время 0 days 00:00:17.136092


({a0: 0.00609796614209715, a1: -7.00570709419740, a2: -0.559143137928326},
 {'MSE': 36.5242879107706})

вот теперь данные почти совпали, но очень много времени

In [55]:
78/12791

In [56]:
-89610/12791

In [57]:
-7152/12791